import biblioteca as _b

margem = ' ' * 4


""""

-- Apagar tabelas dependentes primeiro
DROP TABLE T_MNDSH_TAREFA CASCADE CONSTRAINTS;
DROP TABLE T_MNDSH_METRICA CASCADE CONSTRAINTS;

-- Depois apagar a tabela principal
DROP TABLE T_MNDSH_COLABORADOR CASCADE CONSTRAINTS;


CREATE TABLE T_MNDSH_COLABORADOR (
    id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nr_cpf             VARCHAR2(11 CHAR) NOT NULL UNIQUE,
    nm_colaborador     VARCHAR2(100 CHAR) NOT NULL,
    dt_nascimento      DATE NOT NULL,
    ds_sexo            CHAR(1) NOT NULL CHECK (ds_sexo IN ('M','F')),
    cep                VARCHAR2(9) NOT NULL,
    ds_logradouro      VARCHAR2(150 CHAR) NOT NULL,
    nr_endereco        VARCHAR2(10 CHAR) NOT NULL,
    ds_bairro          VARCHAR2(50 CHAR) NOT NULL,
    ds_cidade          VARCHAR2(50 CHAR) NOT NULL,
    ds_estado          CHAR(2) NOT NULL,
    vl_salario         NUMBER(12,2) NOT NULL CHECK (vl_salario >= 0),
    ds_cargo           VARCHAR2(50 CHAR) NOT NULL,
    dt_admissao        DATE NOT NULL,
    dt_demissao        DATE,
    ds_status          VARCHAR2(20 CHAR) DEFAULT 'Ativo' CHECK (ds_status IN ('Ativo','Inativo')),
    dt_criacao         DATE DEFAULT SYSDATE NOT NULL,
    dt_ultima_modificacao DATE DEFAULT SYSDATE NOT NULL
);

CREATE TABLE T_MNDSH_TAREFA (
    id_tarefa            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nr_cpf               VARCHAR2(11 CHAR) NOT NULL,
    id_colaborador       NUMBER,  -- opcional, para referência direta
    ds_titulo            VARCHAR2(100 CHAR) NOT NULL,
    ds_descricao         VARCHAR2(4000 CHAR),
    ds_prioridade        VARCHAR2(10 CHAR) DEFAULT 'baixa' 
                          CHECK (ds_prioridade IN ('baixa','média','alta')),
    ds_status            VARCHAR2(20 CHAR) DEFAULT 'pendente' 
                          CHECK (ds_status IN ('pendente','em andamento','concluída')),
    dt_prazo             DATE NOT NULL,
    dt_conclusao         DATE,
    dt_criacao           DATE DEFAULT SYSDATE,
    dt_modificacao DATE DEFAULT SYSDATE,
    grau_dificuldade     NUMBER(3,1) CHECK (grau_dificuldade BETWEEN 0 AND 10),
    
    CONSTRAINT fk_tarefa_colaborador_cpf FOREIGN KEY (nr_cpf)
        REFERENCES T_MNDSH_COLABORADOR(nr_cpf)
        ON DELETE CASCADE,
    
    CONSTRAINT fk_tarefa_colaborador_id FOREIGN KEY (id_colaborador)
        REFERENCES T_MNDSH_COLABORADOR(id)
        ON DELETE CASCADE
);


CREATE INDEX idx_tarefa_cpf ON T_MNDSH_TAREFA(nr_cpf);
CREATE INDEX idx_tarefa_status ON T_MNDSH_TAREFA(ds_status);
CREATE INDEX idx_tarefa_prazo ON T_MNDSH_TAREFA(dt_prazo);

CREATE TABLE T_MNDSH_METRICA (
    id_metrica               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nr_cpf                   VARCHAR2(11 CHAR) NOT NULL,
    tipo_metrica             VARCHAR2(50 CHAR) NOT NULL,
    dt_registro              DATE DEFAULT SYSDATE NOT NULL,

    -- PRODUTIVIDADE
    horas_produtivas         NUMBER(3,1),
    nivel_foco               NUMBER(3,1),
    tarefas_concluidas       NUMBER,
    tarefas_andamento        NUMBER,
    tarefas_pendentes        NUMBER,
    concluidas_no_prazo      NUMBER,
    concluidas_atraso        NUMBER,

    -- BEM-ESTAR EMOCIONAL
    estresse                 NUMBER(3,1),
    humor                    NUMBER(3,1),
    energia                  NUMBER(3,1),
    controle_dia             NUMBER(3,1),

    -- SATISFAÇÃO NO TRABALHO
    satisfacao_geral         NUMBER(3,1),
    relacao_colegas          NUMBER(3,1),
    reconhecimento           NUMBER(3,1),
    carga_trabalho           NUMBER(3,1),

    -- QUALIDADE DO SONO
    horas_dormidas           NUMBER(3,1),
    descanso                 NUMBER(3,1),
    despertares              NUMBER(3,1),

    -- BEM-ESTAR FÍSICO
    atividade_fisica         NUMBER(3,1),
    ingestao_agua            NUMBER(3,1),
    intensidade_atividade    NUMBER(3,1),

    CONSTRAINT fk_metrica_colaborador FOREIGN KEY (nr_cpf)
        REFERENCES T_MNDSH_COLABORADOR(nr_cpf)
        ON DELETE CASCADE
);


CREATE INDEX idx_metrica_cpf ON T_MNDSH_METRICA(nr_cpf);
CREATE INDEX idx_metrica_tipo ON T_MNDSH_METRICA(tipo_metrica);
CREATE INDEX idx_metrica_dt ON T_MNDSH_METRICA(dt_registro);


"""

conn = _b.conectarBD()

while True:
    escolha = _b.menu_opcoes(
        "===== MENU PRINCIPAL =====\n",
        ["Administrador", "Colaborador", "Sair"],
        ["administrador", "colaborador", "sair"]
    )
    if escolha == "administrador":
        _b.limpa_tela()
        _b.menu_administrador(conn)
    elif escolha == "colaborador":
        _b.limpa_tela()
        _b.menu_colaborador(conn)
    elif escolha == "sair":
        print(f"\n {margem} Encerrando sistema...\n")
        break

conn.close()


