
-- Criação da tabela COLABORADOR
CREATE TABLE T_MNDSH_COLABORADOR (
    id                 NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nr_cpf             VARCHAR2(11 CHAR) NOT NULL UNIQUE,
    nm_colaborador     VARCHAR2(100 CHAR) NOT NULL,
    dt_nascimento      DATE NOT NULL,
    ds_sexo            CHAR(1) NOT NULL CHECK (ds_sexo IN ('M','F')),
    cep                VARCHAR2(9) NOT NULL,
    ds_logradouro      VARCHAR2(150 CHAR) NOT NULL,
    nr_endereco        VARCHAR2(10 CHAR) NOT NULL,
    ds_bairro          VARCHAR2(50 CHAR) NOT NULL,
    ds_cidade          VARCHAR2(50 CHAR) NOT NULL,
    ds_estado          CHAR(2) NOT NULL,
    vl_salario         NUMBER(12,2) NOT NULL CHECK (vl_salario >= 0),
    ds_cargo           VARCHAR2(50 CHAR) NOT NULL,
    dt_admissao        DATE NOT NULL,
    dt_demissao        DATE,
    ds_status          VARCHAR2(20 CHAR) DEFAULT 'Ativo' CHECK (ds_status IN ('Ativo','Inativo')),
    dt_criacao         DATE DEFAULT SYSDATE NOT NULL,
    dt_ultima_modificacao DATE DEFAULT SYSDATE NOT NULL
);

-- Criação da tabela TAREFA
CREATE TABLE T_MNDSH_TAREFA (
    id_tarefa            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nr_cpf               VARCHAR2(11 CHAR) NOT NULL,
    id_colaborador       NUMBER,  
    ds_titulo            VARCHAR2(100 CHAR) NOT NULL,
    ds_descricao         VARCHAR2(4000 CHAR),
    ds_prioridade        VARCHAR2(10 CHAR) DEFAULT 'baixa' 
                          CHECK (ds_prioridade IN ('baixa','média','alta')),
    ds_status            VARCHAR2(20 CHAR) DEFAULT 'pendente' 
                          CHECK (ds_status IN ('pendente','em andamento','concluída')),
    dt_prazo             DATE NOT NULL,
    dt_conclusao         DATE,
    dt_criacao           DATE DEFAULT SYSDATE,
    dt_modificacao DATE DEFAULT SYSDATE,
    grau_dificuldade     NUMBER(3,1) CHECK (grau_dificuldade BETWEEN 0 AND 10),
    
    CONSTRAINT fk_tarefa_colaborador_cpf FOREIGN KEY (nr_cpf)
        REFERENCES T_MNDSH_COLABORADOR(nr_cpf)
        ON DELETE CASCADE,
    
    CONSTRAINT fk_tarefa_colaborador_id FOREIGN KEY (id_colaborador)
        REFERENCES T_MNDSH_COLABORADOR(id)
        ON DELETE CASCADE
);

-- Índices
CREATE INDEX idx_tarefa_cpf ON T_MNDSH_TAREFA(nr_cpf);
CREATE INDEX idx_tarefa_status ON T_MNDSH_TAREFA(ds_status);
CREATE INDEX idx_tarefa_prazo ON T_MNDSH_TAREFA(dt_prazo);

-- Criação da tabela METRICA
CREATE TABLE T_MNDSH_METRICA (
    id_metrica               NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nr_cpf                   VARCHAR2(11 CHAR) NOT NULL,
    tipo_metrica             VARCHAR2(50 CHAR) NOT NULL,
    dt_registro              DATE DEFAULT SYSDATE NOT NULL,

    -- PRODUTIVIDADE
    horas_produtivas         NUMBER(3,1),
    nivel_foco               NUMBER(3,1),
    tarefas_concluidas       NUMBER,
    tarefas_andamento        NUMBER,
    tarefas_pendentes        NUMBER,
    concluidas_no_prazo      NUMBER,
    concluidas_atraso        NUMBER,

    -- BEM-ESTAR EMOCIONAL
    estresse                 NUMBER(3,1),
    humor                    NUMBER(3,1),
    energia                  NUMBER(3,1),
    controle_dia             NUMBER(3,1),

    -- SATISFAÇÃO NO TRABALHO
    satisfacao_geral         NUMBER(3,1),
    relacao_colegas          NUMBER(3,1),
    reconhecimento           NUMBER(3,1),
    carga_trabalho           NUMBER(3,1),

    -- QUALIDADE DO SONO
    horas_dormidas           NUMBER(3,1),
    descanso                 NUMBER(3,1),
    despertares              NUMBER(3,1),

    -- BEM-ESTAR FÍSICO
    atividade_fisica         NUMBER(3,1),
    ingestao_agua            NUMBER(3,1),
    intensidade_atividade    NUMBER(3,1),

    CONSTRAINT fk_metrica_colaborador FOREIGN KEY (nr_cpf)
        REFERENCES T_MNDSH_COLABORADOR(nr_cpf)
        ON DELETE CASCADE
);

-- Índices
CREATE INDEX idx_metrica_cpf ON T_MNDSH_METRICA(nr_cpf);
CREATE INDEX idx_metrica_tipo ON T_MNDSH_METRICA(tipo_metrica);
CREATE INDEX idx_metrica_dt ON T_MNDSH_METRICA(dt_registro);






-- Criação de dados COLABORADORES
INSERT INTO T_MNDSH_COLABORADOR (
    nr_cpf, nm_colaborador, dt_nascimento, ds_sexo, cep, ds_logradouro,
    nr_endereco, ds_bairro, ds_cidade, ds_estado, vl_salario, ds_cargo,
    ds_jornada, dt_admissao, dt_demissao, ds_status, dt_criacao,
    dt_ultima_modificacao
)
VALUES (
    '05892437120', 'Ana Beatriz Santos', DATE '1996-04-12', 'F', '01001-000',
    'Rua da Consolação', '120', 'Consolação', 'São Paulo', 'SP', 6500.00,
    'Analista de Dados', 'Presencial', DATE '2023-08-10', NULL, 'Ativo',
    DATE '2025-05-04', DATE '2025-05-18'
);

INSERT INTO T_MNDSH_COLABORADOR (
    nr_cpf, nm_colaborador, dt_nascimento, ds_sexo, cep, ds_logradouro,
    nr_endereco, ds_bairro, ds_cidade, ds_estado, vl_salario, ds_cargo,
    ds_jornada, dt_admissao, dt_demissao, ds_status, dt_criacao,
    dt_ultima_modificacao
)
VALUES (
    '29875316409', 'João Pedro Almeida', DATE '1992-10-22', 'M', '22290-030',
    'Av Atlântica', '450', 'Copacabana', 'Rio de Janeiro', 'RJ', 7800.00,
    'Desenvolvedor Back-End', 'Híbrido', DATE '2022-03-14', NULL, 'Ativo',
    DATE '2025-05-10', DATE '2025-05-21'
);

INSERT INTO T_MNDSH_COLABORADOR (
    nr_cpf, nm_colaborador, dt_nascimento, ds_sexo, cep, ds_logradouro,
    nr_endereco, ds_bairro, ds_cidade, ds_estado, vl_salario, ds_cargo,
    ds_jornada, dt_admissao, dt_demissao, ds_status, dt_criacao,
    dt_ultima_modificacao
)
VALUES (
    '45798132670', 'Mariana Castro Lima', DATE '1998-01-15', 'F', '30170-010',
    'Av Amazonas', '998', 'Centro', 'Belo Horizonte', 'MG', 7200.00,
    'Product Owner', 'Remoto', DATE '2021-11-25', NULL, 'Ativo',
    DATE '2025-05-02', DATE '2025-05-19'
);

INSERT INTO T_MNDSH_COLABORADOR (
    nr_cpf, nm_colaborador, dt_nascimento, ds_sexo, cep, ds_logradouro,
    nr_endereco, ds_bairro, ds_cidade, ds_estado, vl_salario, ds_cargo,
    ds_jornada, dt_admissao, dt_demissao, ds_status, dt_criacao,
    dt_ultima_modificacao
)
VALUES (
    '68970215437', 'Ricardo Oliveira Mendes', DATE '1989-07-09', 'M', '80010-000',
    'Rua XV de Novembro', '55', 'Centro', 'Curitiba', 'PR', 9000.00,
    'Tech Lead', 'Híbrido', DATE '2020-07-16', NULL, 'Ativo',
    DATE '2025-05-12', DATE '2025-05-27'
);

INSERT INTO T_MNDSH_COLABORADOR (
    nr_cpf, nm_colaborador, dt_nascimento, ds_sexo, cep, ds_logradouro,
    nr_endereco, ds_bairro, ds_cidade, ds_estado, vl_salario, ds_cargo,
    ds_jornada, dt_admissao, dt_demissao, ds_status, dt_criacao,
    dt_ultima_modificacao
)
VALUES (
    '89015476342', 'Fernanda Ribeiro Costa', DATE '1994-03-07', 'F', '69005-070',
    'Av Eduardo Ribeiro', '340', 'Centro', 'Manaus', 'AM', 6100.00,
    'UX Designer', 'Presencial', DATE '2023-01-05', NULL, 'Ativo',
    DATE '2025-05-06', DATE '2025-05-25'
);




-- Criação de dados TAREFAS
DECLARE
    CURSOR c IS SELECT nr_cpf, id FROM T_MNDSH_COLABORADOR;
    v_data DATE := DATE '2025-06-01';
    v_end  DATE := DATE '2025-07-31';
    v_titulo VARCHAR2(100);
    v_desc   VARCHAR2(4000);
    v_prior  VARCHAR2(10);
    v_status VARCHAR2(20);
    v_criacao DATE;
BEGIN
    WHILE v_data <= v_end LOOP
        IF TO_CHAR(v_data, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') NOT IN ('SAT','SUN') THEN
            FOR col IN c LOOP
                FOR i IN 1..3 LOOP
                    v_titulo := 'Tarefa ' || i || ' - ' || col.nr_cpf || ' (' || TO_CHAR(v_data, 'DD/MM/YYYY') || ')';
                    v_desc   := 'Descrição detalhada da tarefa ' || i || ' para ' || col.nr_cpf;
                    v_prior  := CASE TRUNC(DBMS_RANDOM.VALUE(1,4))
                                WHEN 1 THEN 'baixa'
                                WHEN 2 THEN 'média'
                                ELSE 'alta'
                                END;
                    v_status := CASE TRUNC(DBMS_RANDOM.VALUE(1,4))
                                WHEN 1 THEN 'pendente'
                                WHEN 2 THEN 'em andamento'
                                ELSE 'concluída'
                                END;
                    v_criacao := v_data - TRUNC(DBMS_RANDOM.VALUE(1,3)); -- 1 a 2 dias antes do prazo

                    INSERT INTO T_MNDSH_TAREFA (
                        nr_cpf,
                        id_colaborador,
                        ds_titulo,
                        ds_descricao,
                        ds_prioridade,
                        ds_status,
                        dt_prazo,
                        dt_conclusao,
                        dt_criacao,
                        dt_modificacao,
                        grau_dificuldade
                    )
                    VALUES (
                        col.nr_cpf,
                        col.id,
                        v_titulo,
                        v_desc,
                        v_prior,
                        v_status,
                        v_data,
                        CASE WHEN v_status = 'concluída' THEN v_data ELSE NULL END,
                        v_criacao,
                        v_criacao + 1,
                        TRUNC(DBMS_RANDOM.VALUE(1,11))
                    );
                END LOOP;
            END LOOP;
        END IF;
        v_data := v_data + 1;
    END LOOP;
    COMMIT;
END;
/


-- Criação de dados METRICAS
DECLARE
    CURSOR c_colab IS 
        SELECT nr_cpf 
        FROM T_MNDSH_COLABORADOR
        WHERE ds_status = 'Ativo';
    
    v_data DATE := DATE '2025-06-01';
    v_end  DATE := DATE '2025-07-31';
BEGIN
    WHILE v_data <= v_end LOOP
        IF TO_CHAR(v_data, 'DY', 'NLS_DATE_LANGUAGE=ENGLISH') NOT IN ('SAT','SUN') THEN
            FOR col IN c_colab LOOP

                -- PRODUTIVIDADE
                INSERT INTO t_mndsh_metrica (
                    nr_cpf, tipo_metrica, dt_registro,
                    horas_produtivas, nivel_foco,
                    tarefas_concluidas, tarefas_andamento, tarefas_pendentes,
                    concluidas_no_prazo, concluidas_atraso
                ) VALUES (
                    col.nr_cpf, 'Produtividade', v_data,
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11))
                );

                -- BEM-ESTAR EMOCIONAL
                INSERT INTO t_mndsh_metrica (
                    nr_cpf, tipo_metrica, dt_registro,
                    estresse, humor, energia, controle_dia
                ) VALUES (
                    col.nr_cpf, 'Bem-estar emocional', v_data,
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11))
                );

                -- SATISFAÇÃO NO TRABALHO
                INSERT INTO t_mndsh_metrica (
                    nr_cpf, tipo_metrica, dt_registro,
                    satisfacao_geral, relacao_colegas, reconhecimento, carga_trabalho
                ) VALUES (
                    col.nr_cpf, 'Satisfação no trabalho', v_data,
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11))
                );

                -- QUALIDADE DO SONO
                INSERT INTO t_mndsh_metrica (
                    nr_cpf, tipo_metrica, dt_registro,
                    horas_dormidas, descanso, despertares
                ) VALUES (
                    col.nr_cpf, 'Qualidade do sono', v_data,
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11))
                );

                -- BEM-ESTAR FÍSICO
                INSERT INTO t_mndsh_metrica (
                    nr_cpf, tipo_metrica, dt_registro,
                    atividade_fisica, ingestao_agua, intensidade_atividade
                ) VALUES (
                    col.nr_cpf, 'Bem-estar físico', v_data,
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11)),
                    TRUNC(DBMS_RANDOM.VALUE(0,11))
                );

            END LOOP;
        END IF;
        v_data := v_data + 1;
    END LOOP;

    COMMIT;
END;
/

